### PR TITLE
updates to the library and travis

### PR DESCRIPTION
**Pull request by matzew**
@evanshortiss here we go

### CODE REVIEW

**Comment by matzew** [comment]
@evanshortiss Can you publish, after merging ?

**Comment by matzew** [comment]
@evanshortiss ⚠️  one question, though 

https://github.com/matzew/fh-rest-express-router/blob/bd866db1de33ec284478ca54415e2a074ffc9b59/package.json#L45

With `5.13.1`

**Comment by evanshortiss** [comment]
@matzew I think so if we want to keep everything consistent  👍

**Comment by matzew** [comment]
@evanshortiss done!

**Pull request merged**
